sudo: required
services:
  - docker
  
before_install:
  - docker build -t robmaximize/docker-react -f Dockerfile.dev .

script:
  - docker run robmaximize/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-996988677034"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key:
    secure: "$AWS_SECRET_KEY"
